name: drum1
generator:
  length: 16
  steps: 4
  type: quadrant
  notes:
    - 36
sequences:
  - name: A
    rate: 4
    steps:
      - {pitch: 36, velocity: 103, duration: 8n, mod1: 51, mod2: 29}
      - null
      - null
      - null
      - {pitch: 36, velocity: 97, duration: 8n, mod1: 91, mod2: 34}
      - null
      - null
      - null
      - null
      - null
      - null
      - {pitch: 36, velocity: 38, duration: 8n, mod1: 38, mod2: 12}
      - null
      - null
      - {pitch: 36, velocity: 101, duration: 8n, mod1: 38, mod2: 28}
      - null
  - name: B
    rate: 4
    steps:
      - null
      - {pitch: 36, velocity: 118, duration: 8n, mod1: 37, mod2: 15}
      - null
      - null
      - null
      - null
      - null
      - {pitch: 36, velocity: 111, duration: 8n, mod1: 35, mod2: 110}
      - null
      - null
      - null
      - {pitch: 36, velocity: 62, duration: 8n, mod1: 55, mod2: 53}
      - null
      - {pitch: 36, velocity: 43, duration: 8n, mod1: 92, mod2: 40}
      - null
      - null
  - name: C
    rate: 4
    steps:
      - {pitch: 36, velocity: 110, duration: 8n, mod1: 38, mod2: 20}
      - null
      - null
      - null
      - null
      - null
      - null
      - {pitch: 36, velocity: 66, duration: 8n, mod1: 95, mod2: 106}
      - null
      - {pitch: 36, velocity: 75, duration: 8n, mod1: 60, mod2: 67}
      - null
      - null
      - null
      - null
      - {pitch: 36, velocity: 121, duration: 8n, mod1: 89, mod2: 95}
      - null
