controller:
  device: IAC1
  channel: 7

instruments:
  - name: inst1
    device: IAC1
    channel: 1

loop: rit

scenes:
  - name: default
    repeat: 16
    tracks:
      - name: inst1
        play: [A, B, A, C]
        # play: [D, C]

  - name: rit
    repeat: 16
    tracks:
      - name: inst1
        play: [acc2]