name: openhat

generator:
  length: 16
  steps: 13
  type: euclid
  notes:
    - 39
sequences:
  - name: B
    rate: 4
    steps:
      - {pitch: 39, velocity: 61, duration: 8n, mod1: 53, mod2: 38}
      - null
      - {pitch: 39, velocity: 28, duration: 8n, mod1: 87, mod2: 66}
      - {pitch: 39, velocity: 107, duration: 8n, mod1: 43, mod2: 35}
      - null
      - {pitch: 39, velocity: 62, duration: 8n, mod1: 93, mod2: 12}
      - null
      - {pitch: 39, velocity: 83, duration: 8n, mod1: 17, mod2: 35}
      - null
      - {pitch: 39, velocity: 105, duration: 8n, mod1: 54, mod2: 38}
      - {pitch: 39, velocity: 58, duration: 8n, mod1: 44, mod2: 86}
      - null
      - {pitch: 39, velocity: 93, duration: 8n, mod1: 64, mod2: 101}
      - null
      - {pitch: 39, velocity: 80, duration: 8n, mod1: 30, mod2: 88}
      - null
  - name: A
    rate: 4
    steps:
      - {pitch: 39, velocity: 45, duration: 8n, mod1: 84, mod2: 80}
      - null
      - {pitch: 39, velocity: 44, duration: 8n, mod1: 82, mod2: 91}
      - {pitch: 39, velocity: 113, duration: 8n, mod1: 72, mod2: 93}
      - {pitch: 39, velocity: 89, duration: 8n, mod1: 74, mod2: 45}
      - {pitch: 39, velocity: 83, duration: 8n, mod1: 34, mod2: 81}
      - null
      - {pitch: 39, velocity: 31, duration: 8n, mod1: 111, mod2: 48}
      - {pitch: 39, velocity: 91, duration: 8n, mod1: 12, mod2: 49}
      - {pitch: 39, velocity: 52, duration: 8n, mod1: 12, mod2: 77}
      - {pitch: 39, velocity: 118, duration: 8n, mod1: 36, mod2: 85}
      - null
      - {pitch: 39, velocity: 59, duration: 8n, mod1: 100, mod2: 29}
      - {pitch: 39, velocity: 125, duration: 8n, mod1: 37, mod2: 93}
      - {pitch: 39, velocity: 108, duration: 8n, mod1: 32, mod2: 85}
      - {pitch: 39, velocity: 90, duration: 8n, mod1: 24, mod2: 35}
