# bpm: 120
#scale: 'IIV'
#root: G
controller:
  device: IAC1
  channel: 7

instruments:
  - name: mono1
    device: MOTU828x
    channel: 1
    quantize: true
  - name: kick
    device: MOTU828x
    channel: 14
  - name: snare
    device: MOTU828x
    channel: 14

loop: section1

scenes:
  - name: intro
    repeat: 4
    tracks:
      - name: kick
        master: true
        play: [A]

#      - name: snare
#        play: [half]

      - name: mono1
        play: [intro]

  - name: transition
    repeat: 2
    tracks:
      - name: kick
        master: true
        play: [A]

      - name: snare
        play: [half]

  - name: section1
    repeat: 4
    tracks:
      - name: kick
        master: true
        play: [B, C]

      - name: snare
        play: [half]

      - name: mono1
        follow: kick
        play: [follow1, follow2]