# bpm: 120
#scale: 'IIV'
#root: G
controller:
  device: IAC1
  channel: 7
instruments:
  - name: mono1
    device: MOTU828x
    channel: 1
    quantize: true
  - name: kick
    device: MOTU828x
    channel: 14
scenes:
  - name: intro
    repeat: 4
    tracks:
      - name: kick
        play: [A, B]
      - name: mono1
        follow: kick
        play: [intro]
