name: snare
playback:
  device: MOTU828x
  channel: 14
  rate: 4
generator:
  length: 16
  steps: 4
  type: quadrant
  notes:
    - 38
sequences:
  - name: A
    steps:
      - {pitch: 38, velocity: 115, duration: 8n, mod1: 67, mod2: 81}
      - null
      - null
      - null
      - {pitch: 38, velocity: 44, duration: 8n, mod1: 75, mod2: 88}
      - null
      - null
      - null
      - {pitch: 38, velocity: 38, duration: 8n, mod1: 52, mod2: 70}
      - null
      - null
      - null
      - {pitch: 38, velocity: 120, duration: 8n, mod1: 27, mod2: 73}
      - null
      - null
      - null
  - name: B
    steps:
      - {pitch: 38, velocity: 44, duration: 8n, mod1: 17, mod2: 52}
      - null
      - null
      - {pitch: 38, velocity: 110, duration: 8n, mod1: 30, mod2: 86}
      - null
      - {pitch: 38, velocity: 120, duration: 8n, mod1: 97, mod2: 91}
      - null
      - null
      - {pitch: 38, velocity: 65, duration: 8n, mod1: 73, mod2: 56}
      - null
      - null
      - null
      - null
      - {pitch: 38, velocity: 120, duration: 8n, mod1: 110, mod2: 83}
      - null
      - null
  - name: half
    steps:
      - null
      - null
      - null
      - null
      - {pitch: 38, velocity: 98, duration: 8n, mod1: 29, mod2: 43}
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - {pitch: 38, velocity: 126, duration: 8n, mod1: 99, mod2: 32}
      - null
      - null
      - null
  - name: myTest
    steps:
      - {pitch: 38, velocity: 49, duration: 8n, mod1: 89, mod2: 108}
      - null
      - null
      - null
      - null
      - null
      - {pitch: 38, velocity: 86, duration: 8n, mod1: 59, mod2: 16}
      - null
      - null
      - {pitch: 38, velocity: 26, duration: 8n, mod1: 105, mod2: 14}
      - null
      - null
      - {pitch: 38, velocity: 92, duration: 8n, mod1: 46, mod2: 109}
      - null
      - null
      - null
